### ISSUE TITLE
It seems like using ORM structure can make it even better

### ISSUE THREAD

**Issue by Batuhanaydnn** [Huseyinn1/Reddit-Python-Services#1]
Even if your code is not bad, your code is open to sql injection due to not using ORM. It would be a better approach to use an ORM structure like flask_sqlalchemy instead.

reddit_crawler.py
line 41
c.execute('SELECT * FROM posts WHERE id = ?', (post.id,))

Here, the post.id value is changed, causing SQLi.

A small recommendation code that I wrote with ORM instead.:

class RedditPost(db.model):
    id = db.Column(db.Text, primary_key=True)
    title = db.Column(db.Text)
    content = db.Column(db.Text)

def crawl_posts():
      ...
      ...
      ...
     #Take action for all posts
           for post in new_posts:
                existing_post = Post.query.get(post.id)
    
                if not existing_post:
                    new_post = Post(id=post.id, title=post.title, content=post.selftext)
                    db.session.add(new_post)
                    print(f'New Post Added: {post.title}') # 
    
            db.session.commit()

**Comment by Huseyinn1** [comment]
Evet haklısınız .Tüm kodları orm ile değiştirmiştim fakat orm kullandığımda test kısmını istediğim gibi çalıştıramamıştım .Tüm kodda orm kullandıgım halini mi commitlesem yada sadece reddit_crawler mı orm ile değiştirip commitlesem yada bu haliyle mi bıraksam bilemedim

**Comment by Batuhanaydnn** [comment]
```
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
import praw
import time

app = Flask(__name__)
app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite:///reddit_posts.db'
db = SQLAlchemy(app)

class Post(db.Model):
    id = db.Column(db.Text, primary_key=True)
    title = db.Column(db.Text)
    content = db.Column(db.Text)

def crawl_posts(stop_event):
    client_id = 'client_id'
    client_secret = 'client_secret'
    user_agent = 'ORMIYIDIR'
# Bence bide boş bir reddit hesabı açıp bir uygulama ekle denemek isteyen adamı bidaha client_id ve client_secretla uğraştırma # bence ha uğraştıracaksan bari ne developer console'un nerede olduğunu göster
    subreddit_name = 'popular'

    while not stop_event:
        try:
            reddit = praw.Reddit(client_id=client_id,
                                 client_secret=client_secret,
                                 user_agent='my_user_agent')
            
            subreddit = reddit.subreddit(subreddit_name)
            new_posts = subreddit.new(limit=10)  # Son 10 postu alabiliriz isteğe bağlı olarak değiştirilebilir.
    

            for post in new_posts:
                existing_post = Post.query.get(post.id)
    
                if not existing_post:
                    new_post = Post(id=post.id, title=post.title, content=post.selftext)
                    db.session.add(new_post)
                    # Bunu senin kodunda olduğu için yazdım ama bence gereksiz artı olarak sunucuya yük şu anda localhosttasın ama ilerde canlıya almak istersen güzel değil
                    print(f'Yeni post eklendi: {post.title}')
    
            db.session.commit()
    

            time.sleep(5)
        except Exception as e:
            # Artı olarak exceptionlarında da kesinlikle flask yardımcı fonksiyonu olan jsonify kullan.
            return jsonify({'message' : 'Hata Oluştu'})

if __name__ == '__main__':
    with app.app_context():
        db.create_all()
        crawl_posts(False)
```

ORM olarak örnekte verdiğim yapıyı kullanabilirsin. Eğer çalıştırmada sorun yaşıyorsan büyük ihtimalle circular importla ilgilidir internette dünya kadar makalesi var kankam onlara da bir bak

**Comment by Batuhanaydnn** [comment]
Proje daha iyi olmuş eline sağlık.
